//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Project_3.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RealityServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RealityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHomesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHouseCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHouseStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHouseTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHomesByPreferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRealtorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRealtorsListingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRealtorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListingRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddRealtorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRealtorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback HomeViewRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RealityService() {
            this.Url = global::Project_3.Properties.Settings.Default.Project_3_localhost_RealityService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHomesCompletedEventHandler GetHomesCompleted;
        
        /// <remarks/>
        public event GetHouseCitiesCompletedEventHandler GetHouseCitiesCompleted;
        
        /// <remarks/>
        public event GetHouseStatesCompletedEventHandler GetHouseStatesCompleted;
        
        /// <remarks/>
        public event GetHouseTypesCompletedEventHandler GetHouseTypesCompleted;
        
        /// <remarks/>
        public event GetHomesByPreferenceCompletedEventHandler GetHomesByPreferenceCompleted;
        
        /// <remarks/>
        public event GetRealtorsCompletedEventHandler GetRealtorsCompleted;
        
        /// <remarks/>
        public event GetRealtorsListingsCompletedEventHandler GetRealtorsListingsCompleted;
        
        /// <remarks/>
        public event UpdateRealtorCompletedEventHandler UpdateRealtorCompleted;
        
        /// <remarks/>
        public event GetListingRequestsCompletedEventHandler GetListingRequestsCompleted;
        
        /// <remarks/>
        public event AddRealtorCompletedEventHandler AddRealtorCompleted;
        
        /// <remarks/>
        public event DeleteRealtorCompletedEventHandler DeleteRealtorCompleted;
        
        /// <remarks/>
        public event AddHomeCompletedEventHandler AddHomeCompleted;
        
        /// <remarks/>
        public event DeleteHomeCompletedEventHandler DeleteHomeCompleted;
        
        /// <remarks/>
        public event UpdateHomeCompletedEventHandler UpdateHomeCompleted;
        
        /// <remarks/>
        public event HomeViewRequestCompletedEventHandler HomeViewRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHomes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHomes() {
            object[] results = this.Invoke("GetHomes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHomesAsync() {
            this.GetHomesAsync(null);
        }
        
        /// <remarks/>
        public void GetHomesAsync(object userState) {
            if ((this.GetHomesOperationCompleted == null)) {
                this.GetHomesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHomesOperationCompleted);
            }
            this.InvokeAsync("GetHomes", new object[0], this.GetHomesOperationCompleted, userState);
        }
        
        private void OnGetHomesOperationCompleted(object arg) {
            if ((this.GetHomesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHomesCompleted(this, new GetHomesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHouseCities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHouseCities() {
            object[] results = this.Invoke("GetHouseCities", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHouseCitiesAsync() {
            this.GetHouseCitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetHouseCitiesAsync(object userState) {
            if ((this.GetHouseCitiesOperationCompleted == null)) {
                this.GetHouseCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHouseCitiesOperationCompleted);
            }
            this.InvokeAsync("GetHouseCities", new object[0], this.GetHouseCitiesOperationCompleted, userState);
        }
        
        private void OnGetHouseCitiesOperationCompleted(object arg) {
            if ((this.GetHouseCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHouseCitiesCompleted(this, new GetHouseCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHouseStates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHouseStates() {
            object[] results = this.Invoke("GetHouseStates", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHouseStatesAsync() {
            this.GetHouseStatesAsync(null);
        }
        
        /// <remarks/>
        public void GetHouseStatesAsync(object userState) {
            if ((this.GetHouseStatesOperationCompleted == null)) {
                this.GetHouseStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHouseStatesOperationCompleted);
            }
            this.InvokeAsync("GetHouseStates", new object[0], this.GetHouseStatesOperationCompleted, userState);
        }
        
        private void OnGetHouseStatesOperationCompleted(object arg) {
            if ((this.GetHouseStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHouseStatesCompleted(this, new GetHouseStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHouseTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHouseTypes() {
            object[] results = this.Invoke("GetHouseTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHouseTypesAsync() {
            this.GetHouseTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetHouseTypesAsync(object userState) {
            if ((this.GetHouseTypesOperationCompleted == null)) {
                this.GetHouseTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHouseTypesOperationCompleted);
            }
            this.InvokeAsync("GetHouseTypes", new object[0], this.GetHouseTypesOperationCompleted, userState);
        }
        
        private void OnGetHouseTypesOperationCompleted(object arg) {
            if ((this.GetHouseTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHouseTypesCompleted(this, new GetHouseTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHomesByPreference", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHomesByPreference(string strSQL) {
            object[] results = this.Invoke("GetHomesByPreference", new object[] {
                        strSQL});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHomesByPreferenceAsync(string strSQL) {
            this.GetHomesByPreferenceAsync(strSQL, null);
        }
        
        /// <remarks/>
        public void GetHomesByPreferenceAsync(string strSQL, object userState) {
            if ((this.GetHomesByPreferenceOperationCompleted == null)) {
                this.GetHomesByPreferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHomesByPreferenceOperationCompleted);
            }
            this.InvokeAsync("GetHomesByPreference", new object[] {
                        strSQL}, this.GetHomesByPreferenceOperationCompleted, userState);
        }
        
        private void OnGetHomesByPreferenceOperationCompleted(object arg) {
            if ((this.GetHomesByPreferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHomesByPreferenceCompleted(this, new GetHomesByPreferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRealtors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRealtors() {
            object[] results = this.Invoke("GetRealtors", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRealtorsAsync() {
            this.GetRealtorsAsync(null);
        }
        
        /// <remarks/>
        public void GetRealtorsAsync(object userState) {
            if ((this.GetRealtorsOperationCompleted == null)) {
                this.GetRealtorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRealtorsOperationCompleted);
            }
            this.InvokeAsync("GetRealtors", new object[0], this.GetRealtorsOperationCompleted, userState);
        }
        
        private void OnGetRealtorsOperationCompleted(object arg) {
            if ((this.GetRealtorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRealtorsCompleted(this, new GetRealtorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRealtorsListings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRealtorsListings(string realtorId) {
            object[] results = this.Invoke("GetRealtorsListings", new object[] {
                        realtorId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRealtorsListingsAsync(string realtorId) {
            this.GetRealtorsListingsAsync(realtorId, null);
        }
        
        /// <remarks/>
        public void GetRealtorsListingsAsync(string realtorId, object userState) {
            if ((this.GetRealtorsListingsOperationCompleted == null)) {
                this.GetRealtorsListingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRealtorsListingsOperationCompleted);
            }
            this.InvokeAsync("GetRealtorsListings", new object[] {
                        realtorId}, this.GetRealtorsListingsOperationCompleted, userState);
        }
        
        private void OnGetRealtorsListingsOperationCompleted(object arg) {
            if ((this.GetRealtorsListingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRealtorsListingsCompleted(this, new GetRealtorsListingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRealtor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateRealtor(string strSQL) {
            object[] results = this.Invoke("UpdateRealtor", new object[] {
                        strSQL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRealtorAsync(string strSQL) {
            this.UpdateRealtorAsync(strSQL, null);
        }
        
        /// <remarks/>
        public void UpdateRealtorAsync(string strSQL, object userState) {
            if ((this.UpdateRealtorOperationCompleted == null)) {
                this.UpdateRealtorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRealtorOperationCompleted);
            }
            this.InvokeAsync("UpdateRealtor", new object[] {
                        strSQL}, this.UpdateRealtorOperationCompleted, userState);
        }
        
        private void OnUpdateRealtorOperationCompleted(object arg) {
            if ((this.UpdateRealtorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRealtorCompleted(this, new UpdateRealtorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListingRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetListingRequests(string realtorId) {
            object[] results = this.Invoke("GetListingRequests", new object[] {
                        realtorId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetListingRequestsAsync(string realtorId) {
            this.GetListingRequestsAsync(realtorId, null);
        }
        
        /// <remarks/>
        public void GetListingRequestsAsync(string realtorId, object userState) {
            if ((this.GetListingRequestsOperationCompleted == null)) {
                this.GetListingRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListingRequestsOperationCompleted);
            }
            this.InvokeAsync("GetListingRequests", new object[] {
                        realtorId}, this.GetListingRequestsOperationCompleted, userState);
        }
        
        private void OnGetListingRequestsOperationCompleted(object arg) {
            if ((this.GetListingRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListingRequestsCompleted(this, new GetListingRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddRealtor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddRealtor(string name, string company, string phone) {
            object[] results = this.Invoke("AddRealtor", new object[] {
                        name,
                        company,
                        phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddRealtorAsync(string name, string company, string phone) {
            this.AddRealtorAsync(name, company, phone, null);
        }
        
        /// <remarks/>
        public void AddRealtorAsync(string name, string company, string phone, object userState) {
            if ((this.AddRealtorOperationCompleted == null)) {
                this.AddRealtorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRealtorOperationCompleted);
            }
            this.InvokeAsync("AddRealtor", new object[] {
                        name,
                        company,
                        phone}, this.AddRealtorOperationCompleted, userState);
        }
        
        private void OnAddRealtorOperationCompleted(object arg) {
            if ((this.AddRealtorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRealtorCompleted(this, new AddRealtorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteRealtor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteRealtor(string realtorId) {
            object[] results = this.Invoke("DeleteRealtor", new object[] {
                        realtorId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRealtorAsync(string realtorId) {
            this.DeleteRealtorAsync(realtorId, null);
        }
        
        /// <remarks/>
        public void DeleteRealtorAsync(string realtorId, object userState) {
            if ((this.DeleteRealtorOperationCompleted == null)) {
                this.DeleteRealtorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRealtorOperationCompleted);
            }
            this.InvokeAsync("DeleteRealtor", new object[] {
                        realtorId}, this.DeleteRealtorOperationCompleted, userState);
        }
        
        private void OnDeleteRealtorOperationCompleted(object arg) {
            if ((this.DeleteRealtorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRealtorCompleted(this, new DeleteRealtorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddHome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddHome(string realtorId, string address, string city, string state, string listPrice, string avail, string sqft, string baths, string beds, string type) {
            object[] results = this.Invoke("AddHome", new object[] {
                        realtorId,
                        address,
                        city,
                        state,
                        listPrice,
                        avail,
                        sqft,
                        baths,
                        beds,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddHomeAsync(string realtorId, string address, string city, string state, string listPrice, string avail, string sqft, string baths, string beds, string type) {
            this.AddHomeAsync(realtorId, address, city, state, listPrice, avail, sqft, baths, beds, type, null);
        }
        
        /// <remarks/>
        public void AddHomeAsync(string realtorId, string address, string city, string state, string listPrice, string avail, string sqft, string baths, string beds, string type, object userState) {
            if ((this.AddHomeOperationCompleted == null)) {
                this.AddHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddHomeOperationCompleted);
            }
            this.InvokeAsync("AddHome", new object[] {
                        realtorId,
                        address,
                        city,
                        state,
                        listPrice,
                        avail,
                        sqft,
                        baths,
                        beds,
                        type}, this.AddHomeOperationCompleted, userState);
        }
        
        private void OnAddHomeOperationCompleted(object arg) {
            if ((this.AddHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddHomeCompleted(this, new AddHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteHome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteHome(string homeId) {
            object[] results = this.Invoke("DeleteHome", new object[] {
                        homeId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteHomeAsync(string homeId) {
            this.DeleteHomeAsync(homeId, null);
        }
        
        /// <remarks/>
        public void DeleteHomeAsync(string homeId, object userState) {
            if ((this.DeleteHomeOperationCompleted == null)) {
                this.DeleteHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteHomeOperationCompleted);
            }
            this.InvokeAsync("DeleteHome", new object[] {
                        homeId}, this.DeleteHomeOperationCompleted, userState);
        }
        
        private void OnDeleteHomeOperationCompleted(object arg) {
            if ((this.DeleteHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteHomeCompleted(this, new DeleteHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateHome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateHome(string strSQL) {
            object[] results = this.Invoke("UpdateHome", new object[] {
                        strSQL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateHomeAsync(string strSQL) {
            this.UpdateHomeAsync(strSQL, null);
        }
        
        /// <remarks/>
        public void UpdateHomeAsync(string strSQL, object userState) {
            if ((this.UpdateHomeOperationCompleted == null)) {
                this.UpdateHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateHomeOperationCompleted);
            }
            this.InvokeAsync("UpdateHome", new object[] {
                        strSQL}, this.UpdateHomeOperationCompleted, userState);
        }
        
        private void OnUpdateHomeOperationCompleted(object arg) {
            if ((this.UpdateHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateHomeCompleted(this, new UpdateHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HomeViewRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HomeViewRequest(string realtorId, string homeId, string name, string phone) {
            object[] results = this.Invoke("HomeViewRequest", new object[] {
                        realtorId,
                        homeId,
                        name,
                        phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HomeViewRequestAsync(string realtorId, string homeId, string name, string phone) {
            this.HomeViewRequestAsync(realtorId, homeId, name, phone, null);
        }
        
        /// <remarks/>
        public void HomeViewRequestAsync(string realtorId, string homeId, string name, string phone, object userState) {
            if ((this.HomeViewRequestOperationCompleted == null)) {
                this.HomeViewRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHomeViewRequestOperationCompleted);
            }
            this.InvokeAsync("HomeViewRequest", new object[] {
                        realtorId,
                        homeId,
                        name,
                        phone}, this.HomeViewRequestOperationCompleted, userState);
        }
        
        private void OnHomeViewRequestOperationCompleted(object arg) {
            if ((this.HomeViewRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HomeViewRequestCompleted(this, new HomeViewRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHomesCompletedEventHandler(object sender, GetHomesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHomesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHomesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHouseCitiesCompletedEventHandler(object sender, GetHouseCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHouseCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHouseCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHouseStatesCompletedEventHandler(object sender, GetHouseStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHouseStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHouseStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHouseTypesCompletedEventHandler(object sender, GetHouseTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHouseTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHouseTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHomesByPreferenceCompletedEventHandler(object sender, GetHomesByPreferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHomesByPreferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHomesByPreferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRealtorsCompletedEventHandler(object sender, GetRealtorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRealtorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRealtorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRealtorsListingsCompletedEventHandler(object sender, GetRealtorsListingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRealtorsListingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRealtorsListingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateRealtorCompletedEventHandler(object sender, UpdateRealtorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRealtorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRealtorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetListingRequestsCompletedEventHandler(object sender, GetListingRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListingRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListingRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddRealtorCompletedEventHandler(object sender, AddRealtorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddRealtorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddRealtorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteRealtorCompletedEventHandler(object sender, DeleteRealtorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRealtorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRealtorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddHomeCompletedEventHandler(object sender, AddHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteHomeCompletedEventHandler(object sender, DeleteHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateHomeCompletedEventHandler(object sender, UpdateHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HomeViewRequestCompletedEventHandler(object sender, HomeViewRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeViewRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HomeViewRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591